# Generated by Django 2.2.16 on 2022-10-28 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221025_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Titles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'The score cannot be less than 1'), django.core.validators.MaxValueValidator(10, 'The score cannot be more than 10')], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Year'),
        ),
    ]
