# Generated by Django 2.2.16 on 2022-10-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221019_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesgenres',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Genre'),
        ),
    ]
