# Generated by Django 2.2.16 on 2022-10-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221019_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesgenres',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Genre'),
        ),
    ]
